#!/usr/bin/python3

import argparse
import deefuzzer

from deefuzzer.version import __version__

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--version', help='show version', action="version", version='%(prog)s ' + __version__)
    parser.add_argument('config_file', type=str, help='config file (YAML, XML or JSON)')
    args = parser.parse_args()

    d = deefuzzer.core.DeeFuzzer(args)
    d.start()

if __name__ == '__main__':
    main()

